# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designerGUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1232, 700)
        MainWindow.setStyleSheet("background-color: rgb(232, 232, 232)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("background-color:rgb(185, 185, 185)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scaleRB = QtWidgets.QRadioButton(self.frame)
        self.scaleRB.setObjectName("scaleRB")
        self.verticalLayout.addWidget(self.scaleRB)
        self.scale_frame = QtWidgets.QFrame(self.frame)
        self.scale_frame.setStyleSheet("background-color:rgb(156, 156, 156)")
        self.scale_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scale_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scale_frame.setObjectName("scale_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.scale_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.scale_frame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.scale_frame)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 2)
        self.scxlineEdit = QtWidgets.QLineEdit(self.scale_frame)
        self.scxlineEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scxlineEdit.sizePolicy().hasHeightForWidth())
        self.scxlineEdit.setSizePolicy(sizePolicy)
        self.scxlineEdit.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.scxlineEdit.setObjectName("scxlineEdit")
        self.gridLayout.addWidget(self.scxlineEdit, 1, 1, 1, 1)
        self.scylineEdit = QtWidgets.QLineEdit(self.scale_frame)
        self.scylineEdit.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.scylineEdit.setObjectName("scylineEdit")
        self.gridLayout.addWidget(self.scylineEdit, 2, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.kylineEdit = QtWidgets.QLineEdit(self.scale_frame)
        self.kylineEdit.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.kylineEdit.setObjectName("kylineEdit")
        self.gridLayout_2.addWidget(self.kylineEdit, 1, 3, 1, 1)
        self.kxlineEdit = QtWidgets.QLineEdit(self.scale_frame)
        self.kxlineEdit.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.kxlineEdit.setObjectName("kxlineEdit")
        self.gridLayout_2.addWidget(self.kxlineEdit, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scale_frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scale_frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 4, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.scale_frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_14 = QtWidgets.QLabel(self.scale_frame)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 3, 0, 1, 2)
        self.verticalLayout.addWidget(self.scale_frame)
        self.moveRB = QtWidgets.QRadioButton(self.frame)
        self.moveRB.setObjectName("moveRB")
        self.verticalLayout.addWidget(self.moveRB)
        self.move_frame = QtWidgets.QFrame(self.frame)
        self.move_frame.setStyleSheet("background-color:rgb(156, 156, 156)")
        self.move_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.move_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.move_frame.setObjectName("move_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.move_frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.dxlineEdit = QtWidgets.QLineEdit(self.move_frame)
        self.dxlineEdit.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.dxlineEdit.setObjectName("dxlineEdit")
        self.gridLayout_3.addWidget(self.dxlineEdit, 1, 1, 1, 1)
        self.dylineEdit = QtWidgets.QLineEdit(self.move_frame)
        self.dylineEdit.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.dylineEdit.setObjectName("dylineEdit")
        self.gridLayout_3.addWidget(self.dylineEdit, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.move_frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.move_frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.move_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 0, 0, 1, 2)
        self.verticalLayout.addWidget(self.move_frame)
        self.turnRB = QtWidgets.QRadioButton(self.frame)
        self.turnRB.setObjectName("turnRB")
        self.verticalLayout.addWidget(self.turnRB)
        self.turn_frame = QtWidgets.QFrame(self.frame)
        self.turn_frame.setStyleSheet("background-color:rgb(156, 156, 156)")
        self.turn_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.turn_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.turn_frame.setObjectName("turn_frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.turn_frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.turnxlineEdit = QtWidgets.QLineEdit(self.turn_frame)
        self.turnxlineEdit.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.turnxlineEdit.setObjectName("turnxlineEdit")
        self.gridLayout_4.addWidget(self.turnxlineEdit, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.turn_frame)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 2, 0, 1, 1)
        self.turnylineEdit = QtWidgets.QLineEdit(self.turn_frame)
        self.turnylineEdit.setStyleSheet("background-color: rgb(255, 255, 255)\n"
"")
        self.turnylineEdit.setObjectName("turnylineEdit")
        self.gridLayout_4.addWidget(self.turnylineEdit, 2, 1, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.turn_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11)
        self.gridLayout_4.addLayout(self.verticalLayout_6, 0, 0, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.turn_frame)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.turn_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_8.addWidget(self.label_12)
        self.gridLayout_4.addLayout(self.verticalLayout_8, 3, 0, 1, 2)
        self.anglelineEdit = QtWidgets.QLineEdit(self.turn_frame)
        self.anglelineEdit.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.anglelineEdit.setObjectName("anglelineEdit")
        self.gridLayout_4.addWidget(self.anglelineEdit, 4, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.turn_frame)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 4, 0, 1, 1)
        self.verticalLayout.addWidget(self.turn_frame)
        self.butt_frame = QtWidgets.QFrame(self.frame)
        self.butt_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.butt_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.butt_frame.setObjectName("butt_frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.butt_frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stepBackButt = QtWidgets.QPushButton(self.butt_frame)
        self.stepBackButt.setObjectName("stepBackButt")
        self.horizontalLayout_3.addWidget(self.stepBackButt)
        self.fisrtStateButt = QtWidgets.QPushButton(self.butt_frame)
        self.fisrtStateButt.setObjectName("fisrtStateButt")
        self.horizontalLayout_3.addWidget(self.fisrtStateButt)
        self.gridLayout_6.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.doButt = QtWidgets.QPushButton(self.butt_frame)
        self.doButt.setStyleSheet("font: 11pt \"Noto Serif Armenian\";\n"
"background-color:rgb(91, 0, 0);\n"
"color:rgb(255, 255, 255)")
        self.doButt.setObjectName("doButt")
        self.gridLayout_6.addWidget(self.doButt, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.butt_frame)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.scaleRB.setText(_translate("MainWindow", "Масштабирование "))
        self.label.setText(_translate("MainWindow", "X :"))
        self.label_4.setText(_translate("MainWindow", "                        Центр масштабирования"))
        self.label_2.setText(_translate("MainWindow", " KY :"))
        self.label_5.setText(_translate("MainWindow", " KX :"))
        self.label_3.setText(_translate("MainWindow", "Y :   "))
        self.label_14.setText(_translate("MainWindow", "                 Коэффициенты масштабирования "))
        self.moveRB.setText(_translate("MainWindow", "Перемещение "))
        self.label_6.setText(_translate("MainWindow", " dx :"))
        self.label_7.setText(_translate("MainWindow", " dy :"))
        self.label_8.setText(_translate("MainWindow", "                                 Смещение"))
        self.turnRB.setText(_translate("MainWindow", "Вращение "))
        self.label_10.setText(_translate("MainWindow", " Y :"))
        self.label_11.setText(_translate("MainWindow", "                             Центр поворота"))
        self.label_9.setText(_translate("MainWindow", " X :"))
        self.label_12.setText(_translate("MainWindow", "                              Угол поворота"))
        self.label_13.setText(_translate("MainWindow", "Угол :"))
        self.stepBackButt.setText(_translate("MainWindow", "Шаг назад"))
        self.fisrtStateButt.setText(_translate("MainWindow", "Вернуть к исходному "))
        self.doButt.setText(_translate("MainWindow", "Выполнить"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))

