# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1609, 732)
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 11, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(10, 0))
        self.frame_4.setStyleSheet("background-color: rgb(135, 135, 135)\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout.addWidget(self.frame_4, 1, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(0, 40))
        self.label_13.setStyleSheet("background-color: rgb(181, 181, 181)")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 3, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(300, 0))
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setStyleSheet("background-color: rgb(181, 181, 181)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_11 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(0, 40))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setStyleSheet("background-color: rgb(135, 135, 135)")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.xendEdit = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xendEdit.sizePolicy().hasHeightForWidth())
        self.xendEdit.setSizePolicy(sizePolicy)
        self.xendEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.xendEdit.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.xendEdit.setObjectName("xendEdit")
        self.gridLayout_3.addWidget(self.xendEdit, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 4)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 4, 0, 1, 1)
        self.ystartEdit = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ystartEdit.sizePolicy().hasHeightForWidth())
        self.ystartEdit.setSizePolicy(sizePolicy)
        self.ystartEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.ystartEdit.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.ystartEdit.setObjectName("ystartEdit")
        self.gridLayout_3.addWidget(self.ystartEdit, 2, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 7, 0, 1, 1)
        self.bEdit = QtWidgets.QLineEdit(self.groupBox)
        self.bEdit.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.bEdit.setObjectName("bEdit")
        self.gridLayout_3.addWidget(self.bEdit, 8, 1, 1, 3)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 8, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.xstartEdit = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xstartEdit.sizePolicy().hasHeightForWidth())
        self.xstartEdit.setSizePolicy(sizePolicy)
        self.xstartEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.xstartEdit.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.xstartEdit.setObjectName("xstartEdit")
        self.gridLayout_3.addWidget(self.xstartEdit, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 5, 0, 1, 4)
        self.yendEdit = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yendEdit.sizePolicy().hasHeightForWidth())
        self.yendEdit.setSizePolicy(sizePolicy)
        self.yendEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.yendEdit.setStyleSheet("background-color: rgb(255, 255, 255)\n"
"")
        self.yendEdit.setObjectName("yendEdit")
        self.gridLayout_3.addWidget(self.yendEdit, 4, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 2, 1, 1)
        self.rEdit = QtWidgets.QLineEdit(self.groupBox)
        self.rEdit.setStyleSheet("background-color: rgb(255, 255, 255)\n"
"")
        self.rEdit.setObjectName("rEdit")
        self.gridLayout_3.addWidget(self.rEdit, 6, 1, 1, 3)
        self.gEdit = QtWidgets.QLineEdit(self.groupBox)
        self.gEdit.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.gEdit.setObjectName("gEdit")
        self.gridLayout_3.addWidget(self.gEdit, 7, 1, 1, 3)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 4, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 6, 0, 1, 1)
        self.colorCHB = QtWidgets.QCheckBox(self.groupBox)
        self.colorCHB.setObjectName("colorCHB")
        self.gridLayout_3.addWidget(self.colorCHB, 9, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setStyleSheet("background-color: rgb(135, 135, 135)")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.decimalRB = QtWidgets.QRadioButton(self.groupBox_2)
        self.decimalRB.setObjectName("decimalRB")
        self.verticalLayout.addWidget(self.decimalRB)
        self.intRB = QtWidgets.QRadioButton(self.groupBox_2)
        self.intRB.setObjectName("intRB")
        self.verticalLayout.addWidget(self.intRB)
        self.deleteStepRB = QtWidgets.QRadioButton(self.groupBox_2)
        self.deleteStepRB.setObjectName("deleteStepRB")
        self.verticalLayout.addWidget(self.deleteStepRB)
        self.libRB = QtWidgets.QRadioButton(self.groupBox_2)
        self.libRB.setObjectName("libRB")
        self.verticalLayout.addWidget(self.libRB)
        self.ddaRB = QtWidgets.QRadioButton(self.groupBox_2)
        self.ddaRB.setObjectName("ddaRB")
        self.verticalLayout.addWidget(self.ddaRB)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setStyleSheet("background-color: rgb(135, 135, 135)")
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stepEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.stepEdit.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.stepEdit.setObjectName("stepEdit")
        self.gridLayout_2.addWidget(self.stepEdit, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 1, 0, 1, 1)
        self.cmpCHB = QtWidgets.QCheckBox(self.groupBox_3)
        self.cmpCHB.setObjectName("cmpCHB")
        self.gridLayout_2.addWidget(self.cmpCHB, 0, 0, 1, 2)
        self.lineCHB = QtWidgets.QCheckBox(self.groupBox_3)
        self.lineCHB.setObjectName("lineCHB")
        self.gridLayout_2.addWidget(self.lineCHB, 2, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.doButt = QtWidgets.QPushButton(self.frame)
        self.doButt.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(113, 0, 0)")
        self.doButt.setObjectName("doButt")
        self.verticalLayout_2.addWidget(self.doButt)
        self.clearButt = QtWidgets.QPushButton(self.frame)
        self.clearButt.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255)")
        self.clearButt.setObjectName("clearButt")
        self.verticalLayout_2.addWidget(self.clearButt)
        self.gridLayout.addWidget(self.frame, 0, 0, 2, 1)
        self.cmpFR = QtWidgets.QFrame(self.centralwidget)
        self.cmpFR.setStyleSheet("background-color: rgb(29, 29, 29)")
        self.cmpFR.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cmpFR.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cmpFR.setObjectName("cmpFR")
        self.gridLayout.addWidget(self.cmpFR, 1, 3, 1, 1)
        self.LineFR = QtWidgets.QFrame(self.centralwidget)
        self.LineFR.setAutoFillBackground(False)
        self.LineFR.setStyleSheet("background-color: rgb(29, 29, 29)")
        self.LineFR.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LineFR.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LineFR.setObjectName("LineFR")
        self.gridLayout.addWidget(self.LineFR, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(0, 40))
        self.label_12.setStyleSheet("background-color: rgb(181, 181, 181)")
        self.label_12.setTextFormat(QtCore.Qt.AutoText)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_13.setText(_translate("MainWindow", " Сравнение визуальных характеристик "))
        self.label_11.setText(_translate("MainWindow", "Управление "))
        self.groupBox.setTitle(_translate("MainWindow", "Параметры прямой"))
        self.label.setText(_translate("MainWindow", " Координаты начала прямой"))
        self.label_6.setText(_translate("MainWindow", "x: "))
        self.label_9.setText(_translate("MainWindow", "G: "))
        self.label_10.setText(_translate("MainWindow", "B: "))
        self.label_3.setText(_translate("MainWindow", "x: "))
        self.label_7.setText(_translate("MainWindow", "Цвет линии"))
        self.label_4.setText(_translate("MainWindow", "Координаты конца прямой "))
        self.label_2.setText(_translate("MainWindow", "y: "))
        self.label_5.setText(_translate("MainWindow", "y: "))
        self.label_8.setText(_translate("MainWindow", "R: "))
        self.colorCHB.setText(_translate("MainWindow", "цвет фона "))
        self.groupBox_2.setTitle(_translate("MainWindow", "Выбор алгоритма"))
        self.decimalRB.setText(_translate("MainWindow", "Алгоритм Брезенхэма с действительными числами"))
        self.intRB.setText(_translate("MainWindow", "Алгоритм Брезенхэма с целыми числами"))
        self.deleteStepRB.setText(_translate("MainWindow", "Алгоритм Брезенхэма с удалением ступенчатости"))
        self.libRB.setText(_translate("MainWindow", "Алгоритм из библиотеки"))
        self.ddaRB.setText(_translate("MainWindow", "ЦДА"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Сравнение характеристик "))
        self.label_14.setText(_translate("MainWindow", "Шаг в градусах"))
        self.cmpCHB.setText(_translate("MainWindow", "Сравнить визуальные характеристики"))
        self.lineCHB.setText(_translate("MainWindow", "Нарисовать отрезок"))
        self.doButt.setText(_translate("MainWindow", "Выполнить"))
        self.clearButt.setText(_translate("MainWindow", "Очистить"))
        self.label_12.setText(_translate("MainWindow", "Линия"))

